name = "sinal"
version = "0.1.0"
target = "erlang"
gleam = ">= 1.18.0"
internal_modules = ["sinal/internal", "sinal/internal/*"]
licenses = ["Apache-2.0"]
description = "A strongly-typed take on Erlang :telemetry, built for Gleam's generics instead of dynamic maps and atoms."
repository = { type = "github", user = "gleam-dream", repo = "sinal" }

[erlang]
extra_applications = ["crypto"]

[dependencies]
gleam_stdlib = ">= 0.70.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
telemetry = ">= 1.4.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
