#let terms = (
  (slug: "term-event", title: [Event], body: [An immutable typed definition of one telemetry name and its measurement and metadata shapes. A definition is distinct from an occurrence emitted under that name.]),
  (slug: "term-fields", title: [Fields], body: [A bidirectional description of the declared keys in one native telemetry map and the caller value represented by those keys.]),
  (slug: "term-measurements", title: [Measurements], body: [The numeric or application-defined values recorded as the first map of a telemetry occurrence.]),
  (slug: "term-metadata", title: [Metadata], body: [The descriptive and identifying values recorded as the second map of a telemetry occurrence.]),
  (slug: "term-subscription", title: [Subscription], body: [An immutable registration description whose typed callback, failure observer, and selected event definitions are already bound.]),
  (slug: "term-attachment", title: [Attachment], body: [A handle naming one native handler registration. A copied handle retains the same identifier after that registration disappears.]),
  (slug: "term-handler-failure", title: [Handler failure], body: [A malformed measurement, malformed metadata, or caller-defined error returned by a typed handler. Unexpected exceptions are outside this sum.]),
  (slug: "term-subscription-plan", title: [Subscription plan], body: [An ordered group of subscriptions with a reporter for cleanup failures that accompany a catchable exception.]),
  (slug: "term-subscription-scope", title: [Subscription scope], body: [One acquisition, work, and cleanup lifetime for a subscription plan. It owns the registrations it successfully acquired.]),
  (slug: "term-correlation", title: [Correlation], body: [An opaque UTF-8 value of one to 128 bytes identifying an application-selected unit of work across observations. It is distinct from a package's own invocation identifier.]),
  (slug: "term-span", title: [Span], body: [An immutable definition of the start, stop, and exception observations surrounding one call of instrumented work.]),
  (slug: "term-span-context", title: [Span context], body: [A native identity shared by the start and terminal observations of one span invocation. It supplies equality rather than trace parentage.]),
  (slug: "term-forwarder", title: [Forwarder], body: [An immutable configuration for a named, capacity-bounded telemetry execution process. Its running process lifetime is a forwarder incarnation.]),
  (slug: "term-forwarder-incarnation", title: [Forwarder incarnation], body: [One running lifetime of a forwarder process, with its own event destination and admission counters.]),
  (slug: "term-route", title: [Route], body: [A node-wide binding from an event-name prefix to a forwarder. The most specific matching prefix selects the destination.]),
  (slug: "term-in-flight-event", title: [In-flight event], body: [A forwarded occurrence admitted to one incarnation whose dispatch has not finished. Capacity includes both queued and executing occurrences.]),
  (slug: "term-drop-report", title: [Drop report], body: [A best-effort observation of capacity refusals, unavailable destinations, and a restart's estimate of lost in-flight events. It is a diagnostic count rather than a delivery receipt.]),
)
